### ISSUE TITLE
Document incomplete?

### ISSUE THREAD

**Issue by didxga** [draftcode/ijaas#5]
I followed the 6 steps installation guide, but when I open vim, trying some Java code, I could not get code autocomplete. Am I missing something?

I am using MacOS, IntelliJ IDEA 2017.1.5

**Comment by draftcode** [comment]
C-x C-o does nothing?

**Comment by didxga** [comment]
@draftcode 
no. My vim runtime path is:
`runtimepath=~/.vim,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,~/.vim/after,~/Documents/code/github/ijaas/vim`
the last path is the path to ijaas/vim folder, and my IntelliJ IDEA is running.

**Comment by draftcode** [comment]
Please create and open some incomplete .java file and execute ":call ijaas#buf_write_post()" or ":call ijaas#organize_import()". buf_write_post will check the compilation error and organize_import tries to find a missing import. If those functions do not exist, your Vim installation seems wrong. If those functions complain about other things, the problem is between Vim and InteiiJ or on the IntelliJ side.

**Comment by didxga** [comment]
I got some error while run `:call ijaas#organize_import()`

`Error detected while processing /Users/carterchen/Documents/code/github/ijaas/vim/autoload/ijaas.vim:
line   20:
E117: Unknown function: ch_open
E15: Invalid expression: ch_open('localhost:5800')
Error detected while processing function ijaas#organize_import[1]..ijaas#call:
line    1:
E121: Undefined variable: s:ch
E116: Invalid arguments for function ch_info(s:ch)
E15: Invalid expression: ch_info(s:ch)`

**Comment by draftcode** [comment]
I guess your vim doesn't have +channel? Can you check that with ":version"?

**Comment by didxga** [comment]
Yes you are right, The MacOS native vim doesn't have channel. I installed Homebrew version of Vim, it does have channel.

Then I started Intellij,  started new terminal, and vim App.java, but I still could not seem to get autocompletion, when I do :call ijaas#buf_write_post(), I got 

`Error detected while processing function ijaas#buf_write_post[1]..ijaas#call:
line   10:
E605: Exception not caught: ijaas: Timeout`

**Comment by draftcode** [comment]
I think the time out is a known issue ("Everything is slow" in KNOWN_ISSUES.md). If you try this with a small file or try several times, it eventually succeeds. Also something is stuck occasionally, and you need to press the cancel button on the UI. IntelliJ is mostly written assuming that there's always GUI, so this plugin is doing something odd to them. I hope that they reorganize the code and add a native support for language server protocol in some way and obsolete this plugin. (That is, I'm thinking this plugin as a stopgap solution until LSP and its impls get mature. I considered implementing LSP, but I couldn't find a way to implement multi-choice codeAction like OrganizeImports).
