### ISSUE TITLE
Any JDK & Gradle version required?

### ISSUE THREAD

**Issue by ghost** [draftcode/ijaas#6]
I was using JDK8 and gradle 2.0 to run "gradle buildPlugin" but it failed with below msg:
_Caused by: org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'IntelliJPlugin'.
        at org.gradle.api.internal.plugins.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:67)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:109)_

May I know a correct combination of JDK & Gradle that works well for it? thanks.

**Comment by didxga** [comment]
@shihty5 I am using JDK8 and Gradle 4.3.1, it works for me. you may consider to upgrade your Gradle.

**Comment by draftcode** [comment]
Please use Gradle 2.1 or higher. This uses https://github.com/JetBrains/gradle-intellij-plugin and it cannot  find that plugin with Gradle 2.0.
