### ISSUE TITLE
Plugin incompatible with installation

### ISSUE THREAD

**Issue by sebglazebrook** [draftcode/ijaas#8]
I've been able to follow the readme but when I try to install the plugin zip file I get an error:

```
Plugin 'ijaas' is incompatible with this installation
```

any ideas?

**Comment by draftcode** [comment]
In `build.gradle`, there's a section called `patchPluginXml`. Update `untilBuild` to `183.*` and try again.

**Comment by draftcode** [comment]
Updated the builld.gradle
